-- Nexa Code AI Phase 6
-- Run this in Supabase SQL Editor before using cross-device sync.

create table if not exists public.user_data (
  id bigint generated by default as identity primary key,
  user_id uuid not null unique references auth.users(id) on delete cascade,
  github_token text,
  vercel_token text,
  api_keys jsonb not null default '{}'::jsonb,
  chats jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

alter table public.user_data enable row level security;

drop policy if exists "Users can read their own NCA data" on public.user_data;
create policy "Users can read their own NCA data"
  on public.user_data for select
  using (auth.uid() = user_id);

drop policy if exists "Users can insert their own NCA data" on public.user_data;
create policy "Users can insert their own NCA data"
  on public.user_data for insert
  with check (auth.uid() = user_id);

drop policy if exists "Users can update their own NCA data" on public.user_data;
create policy "Users can update their own NCA data"
  on public.user_data for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create index if not exists user_data_user_id_idx on public.user_data(user_id);
